#!/usr/bin/env bash

set -e

VIEWER=imv
VIEWER_OPTS="$@ -bffffff"
QRCMD=qrencode
QRCMD_OPTS="-t PNG32 -s 10 -m 3"


tmpdir=$(mktemp -d /tmp/qrclip.XXXXX)
pngfile=${tmpdir}/qrcode.png

"${QRCMD}" ${QRCMD_OPTS} -o "${pngfile}"
"${VIEWER}" ${VIEWER_OPTS} "${pngfile}"

if [ -e "${tempdir}" ] ; then
    rm -rf "${tempdir}"
fi
