#!/usr/bin/env bash

# Get battery status from acpi
# $BLOCK_INSTANCE is an option that can be set in i3block.conf
BATCALL=$(acpi -b | grep "Battery $BLOCK_INSTANCE")

# Set Status and Percentage variables
STATUS=$(echo $BATCALL | cut -d':' -f 2 | cut -d',' -f 1)
PERCENT=$(echo $BATCALL | cut -d',' -f 2 | tr -d %)

# Set Icon
if [ $STATUS == "Discharging" ] ; then
    if [ $PERCENT -ge 90 ] ; then
        ICON=""
    elif [ $PERCENT -ge 65 ] ; then
        ICON=""
    elif [ $PERCENT -ge 40 ] ; then
        ICON=""
    elif [ $PERCENT -ge 15 ] ; then
        ICON=""
    elif [ $PERCENT -lt 15 ] ; then
        ICON=""
    fi
elif [ $STATUS == "Charging" ] || [ $STATUS == "Full" ] ; then
    ICON=""
fi

echo "$ICON $PERCENT%" # Full text label
echo "$ICON" # Short text label (Used when status line gets too long)

# Set color value for the above
if [ $PERCENT -ge 85 ] ; then
    echo "#9FA91F"
elif [ $PERCENT  -ge 50 ] ; then
    echo "#FFBF00"
elif [ $PERCENT  -ge 20 ] ; then
    echo "#FF7E00"
elif [ $PERCENT  -lt 20 ] ; then
    echo "#FF033E"
fi
[ $PERCENT  -lt 10 ] && exit 33
exit 0
