#!/usr/bin/bash


: "${REMOTE_CHECK_IP:=8.8.8.8}"
: "${JQ_CMD:=jq}"

: "${CONFIG_FILE:=$XDG_CONFIG_HOME/network/gwmaps.json}"
if [ ! -f "$CONFIG_FILE" ] ; then
    printf "Config %s not found" "$CONFIG_FILE" 1>&2
    exit 2
fi


get_vpn(){
    "$JQ_CMD" -r --arg ip "$1" '.vpn[$ip]' "${CONFIG_FILE}"
}

get_network(){
    "$JQ_CMD" -r --arg ip "$1" '.networks[$ip]' "${CONFIG_FILE}"
}

ROUTE="$(ip route get "$REMOTE_CHECK_IP")"

if [ "$ROUTE" = "RTNETLINK answers: Network is unreachable" ] ; then
    echo "down"
    exit 33
else
    gw="$(echo "${ROUTE}" | awk '{ print $5 }')"
    via="$(echo "${ROUTE}" | awk '{ print $3 }')"
    network="$(get_network "$via")"

    case $network in
        vpn)
            vpn="$(get_vpn "$gw")"
            printf " %s\n" "$vpn"
            ;;
        *)
            [ "$network" = "null" ] && network="$via"
            printf "%s\n" "$network"
            ;;
    esac
fi

