#!/usr/bin/sh


: "${REAL_SCRIPT:=shortnote}"

#notify-send "$(printenv)"

case $BLOCK_BUTTON in
    1)
        $REAL_SCRIPT termadd
        $REAL_SCRIPT print | head -n 1
        ;;
    2)
        echo 2
        ;;
    3)
        $REAL_SCRIPT delete
        $REAL_SCRIPT print | head -n 1
        exit 33
        ;;
    *)
        $REAL_SCRIPT print
        ;;
esac
