#!/usr/bin/sh


#notify-send "$(printenv)"

case $BLOCK_BUTTON in
    1)
        shortnote termadd
        shortnote print | head -n 1
        ;;
    2)
        echo 2
        ;;
    3)
        shortnote delete
        exit 33
        ;;
    *)
        shortnote print
        ;;
esac
