#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=$HOME/.mpv/socket" \
	calcurse="calcurse -D ~/.config/calcurse" \
        code="GDK_BACKEND=x11 code" \
        chrome="GDK_BACKEND=x11 google-chrome" \
	magit="nvim -c MagitOnly" \
        netlist="netctl-auto list" \
	p="sudo pacman" \
        wp="wal -q -i" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	e="$EDITOR" \
	v="$EDITOR" \
        vi="$EDITOR" \
        vw="vimwiki" \
	x="imv *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '~/Videos/yt/%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer --player=mpv" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
        translate="translate-shell -l de -s de -t en de:en" \
        pacman="sudo pacman --color=auto" \
        pomo="touch ~/.cache/pomodoro_session" \
        qutebrowser="QT_QPA_PLATFORM=wayland-egl qutebrowser" \
        x11="GDK_BACKEND=x11" \
        wayland="GDK_BACKEND=wayland"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

fv() { fzf | xargs -r -I % $EDITOR % ;}

## CD Helper

fd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
  ls
}

# fdr - cd to selected parent directory
fdr() {
  get_parent_dirs() {
    if [[ -d "${1}" ]]; then echo "$1"; else return; fi
    if [[ "${1}" == '/' ]]; then
      echo ".."
    else
      get_parent_dirs $(dirname "$1")
    fi
  }
  DIR=$(get_parent_dirs $(realpath "${1:-$PWD}") | fzf-tmux )
  cd "$DIR"
}

cdans() {
    dir=$(find ~/ansible/ -mindepth 1 -maxdepth 2 -type d  -print0 | fzf --read0 --preview='tree {}')
    cd "$dir"
    pwd
    ls
}

## # fh - repeat history
fh() {
  eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -r 's/ *[0-9]*\*? *//' | sed -r 's/\\/\\\\/g')
}
