#!/usr/bin/bash
## Configuration for interactive shells only!
## Most likely aliases, Prompts and key bindings

export HISTSIZE=100000
export HISTTIMEFORMAT="%F %T "
export HISTCONTROL=ignoreboth:erasedups

PS1='[\u@\h \W]\$ '

## Files to be included
BASHCFG="$HOME/.config/bash"
HELPER_INC="$BASHCFG/helper.bash $BASHCFG/multimedia.sh $HOME/.bash_aliases $BASHCFG/bitbucket.bash"
## Include helper
for inc in $HELPER_INC ; do
	if [ -e "$inc" ] ; then
		source "$inc"
	else
		echo "Something is wrong, I need includes and \`$inc\` is missing."
		echo "Errors may follow."
	fi
done
unset -v inc

## Aliases

alias ls='ls --color=auto'
alias ll="ls -lsa"
alias rss="newsbeuter"
alias hl="/usr/bin/highlight -O ansi"

alias pass='PASSWORD_STORE_ENABLE_EXTENSIONS=true pass'

alias http_serv="/usr/bin/python3 -m http.server 8082"
alias gcav="git commit -av"
alias gipu="git push"
alias gl="git log"
alias ggrep="git grep"
alias yaourt-upgrade="/usr/bin/yaourt -Syua"
alias ync='yaourt --noconfirm'

alias tw="/usr/bin/timew"
alias tws="/usr/bin/timew summary"
alias tls="/usr/bin/task ls"

alias pepe="perl -pe"
alias vimwiki="nvim -c +VimwikiIndex"

alias fixscreen="xset dpms force off"

alias se="sudo -e"
alias si="sudo -i"

alias lstimer="systemctl list-timers"

alias xmutt="st -f \"Roboto Mono Light:size=12\" -e mutt"
alias xst="st -f \"Roboto Mono Light:size=12\""

alias 3dcam="cvlc -q https://toke:xpal,3456@octo.home.kerpe.net/webcam/?action=stream > /dev/null"

alias ppaste="curl -F c=@- https://ptpb.pw/"

alias git-context-private="export GIT_COMMITTER_EMAIL=toke@toke.de GIT_AUTHOR_EMAIL=toke@toke.de"
alias git-context-work="export GIT_COMMITTER_EMAIL=thomas.kerpe@1und1.de GIT_AUTHOR_EMAIL=thomas.kerpe@1und1.de"

alias usystemctl="systemctl --user"
alias usys="usystemctl"

alias debian="sudo systemd-nspawn -bD /srv/chroot/jessie"

alias zeus='dig +noall +answer @zeusmw.tool.1and1.com'
#alias winjumper="rdesktop -d "united" -u "tkerpe" -p "$(pass 1und1/owa.extranet.1and1.org/tkerpe|head -n 1)" winjumperng.united.domain'
# z.B. in die .bashrc

alias 1pass='PASSWORD_STORE_DIR=$HOME/.password-store-1und1 PASSWORD_STORE_GIT=$HOME/.password-store-1und1 pass'

# z.B. .bashrc oder .bash_completion
source /usr/share/bash-completion/completions/pass
_1pass(){
    PASSWORD_STORE_DIR=$HOME/.password-store-1und1 _pass
}
complete -o filenames -o nospace -F _1pass 1pass

## GTD via https://taskwarrior.org/news/news.20150627.html
## use as "in"
alias in='task add +in'

[[ -e "/usr/bin/fzf-tmux" ]] && alias vo='vim $(fzf-tmux)'

[[ -e "/usr/bin/nvim" ]] && alias vi="/usr/bin/nvim"
[[ -e "/usr/bin/nvim" ]] && alias vim="/usr/bin/nvim"
[[ -e "/usr/bin/gpwsafe" ]] && alias pw="/usr/bin/gpwsafe"
[[ -e "/usr/bin/translate-shell" ]] && alias translate="/usr/bin/translate-shell"

[[ -e "${HOME}/git/puppet-dev-env/bin/nessie" ]] &&  nessie="${HOME}/git/puppet-dev-env/bin/nessie"

## Docker specific aliases
if [[ $(command -v "docker") ]] ; then
    # Kill all running containers.
    alias docker-killall='docker kill $(docker ps -q)'

    # Delete all stopped containers.
    alias docker-cleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'

    # Delete all untagged images.
    alias docker-cleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'

    # Delete all stopped containers and untagged images.
    alias docker-clean='docker-cleanc || true && docker-cleani'
fi



## NEEDS: html-xml-utils
webpage_title (){
    wget -qO- "$*" | hxselect -s '\n' -c  'title' 2>/dev/null
}

read_and_review (){
    link="$1"
    title=$(webpage_title $link)
    echo $title
    descr="\"Read and review: $title\""
    id=$(task add +next +rnr "$descr" | sed -n 's/Created task \(.*\)./\1/p')
    task "$id" annotate "$link"
}

alias rnr=read_and_review


if [[ -e $BASHCFG/completion.d/ ]] ; then
    source $BASHCFG/completion.d/*
fi


